Admin page UI and components
cshub-yorku/merchStore pull request #21
Opened 2023-02-28 06:13 UTC by namanrai

# Pull Request Description Template

Before making your pull request, these descriptions should be included to allow the reviewer to reference.
<ol>
    <li>Added the UI and the different components for the admin page and linked  it with the login/signup</li>
        <ul>
            <li>Added components for the Profile, Address and Order History Components and general styling for the admin page</li>
        </ul>
    <li>Changes can be found in the components folder under frontend</li>
        <ul>
            <li>merchStore\frontend\src\components\Admin.js</li>
        </ul>
    <li>Some changes are affected to the navigation of the page</li>
        <ul>
            <li>Link it with the User Login and Authentication in future and also access to the user account data</li>
        </ul>
</ol>

2023-02-28 22:04 UTC, DROFEL approved these changes, later dismissed
All good!

Can you please look into .gitignore and add .vscode folder. Lets keep repo clean :)

2023-02-28 22:06 UTC, Rickie457 approved these changes
LGTM

2023-02-28 22:10 UTC, DROFEL commented on frontend/src/components/ProductPopup.js
> +                sx={{
This one concerns me.

2023-02-28 22:10 UTC, DROFEL requested changes
Can you please resolve conflict for product popup before i can approve

2023-03-03 02:08 UTC, namanrai commented
Fixed merge conflicts. Please re-review. Thank You

2023-03-04 20:48 UTC, ShafinMahmudCS approved these changes

2023-03-04 21:39 UTC, Rickie457 reviewed
Your ProductPopup.js is behind some changes. Pull the new changes before pushing to the development branch to avoid deleting the Popup changes.

2023-03-04 22:57 UTC, namanrai commented
Made the changes and rebased the branch to development.

> Your ProductPopup.js is behind some changes. Pull the new changes before pushing to the development branch to avoid deleting the Popup changes.

Made the changes and rebased the branch to development.

2023-03-05 01:03 UTC, DROFEL approved these changes
good

2023-03-05 01:06 UTC, merged