Cart Drawer Implementation
cshub-yorku/merchStore pull request #26
Opened 2023-03-31 22:47 UTC by Rickie457

Implemented the Figma design for the Cart Drawer

2023-04-01 01:39 UTC, namanrai approved these changes

2023-04-01 03:52 UTC, DROFEL commented on backend/src/main/java/com/MerchStore/backend/App/Driver.java
> +package com.MerchStore.backend.App;
are you supposed to make any changes to backend?

2023-04-01 03:52 UTC, DROFEL commented on frontend/src/components/Product.js
> +    <Box className="product" color="background">
These are legacy files can you remove this one and all css that are included in this merge

2023-04-01 03:59 UTC, DROFEL requested changes
Remove backend files commit

2023-04-01 21:12 UTC, ShafinMahmudCS requested changes
@Rickie457 You created this branch from an early version of development. You should have pulled the updates from the development branch. Many files were removed or renamed so in your pull request all of those are showing as new files added.

2023-04-02 22:28 UTC, Rickie457 reviewed
resolved conflicts

2023-04-02 22:40 UTC, DROFEL approved these changes
good

2023-04-03 01:22 UTC, ShafinMahmudCS approved these changes

2023-04-03 06:30 UTC, merged