Minor fixes
cshub-yorku/merchStore pull request #29
Opened 2023-04-02 00:58 UTC by namanrai

# Frontend Fixes

<ol>
    <li>Multiple Fixes for the frontend</li>
    <li>In the Frontend Directory</li>
        <ul>
            <li>\merchStore\frontend\src\components</li>
        </ul>
    <ul>
           <li>Fixed the Navbar overflow</li>
           <li>Fixed the cross in the Navbar</li>
           <li>Fixed margin and overflow in the Footer</li>
           <li>Fixed the overflow in the signup popup</li>
           <li>Fixed the text overflow in the Admin Page</li>
           <li>Removed Address component from the Admin Page</li>
           <li>Converted Footer.css to MUI components</li>
    </ul>
    
</ol>

2023-04-02 01:25 UTC, DROFEL approved these changes
LGTM!

2023-04-02 01:25 UTC, DROFEL commented on frontend/src/components/Footer.js
> +        <Box sx={{  paddingTop: '30px',
Ideally you would want to put styles in separate .js file in styles folder and then import that object but its also fine

2023-04-03 01:27 UTC, ShafinMahmudCS requested changes
Please resolve conflicts

2023-04-04 00:35 UTC, namanrai commented
I have fixed the merge conflicts but the development branch has errors right now. Do you want me to merge right now or that's fixed?

2023-04-04 06:24 UTC, ShafinMahmudCS approved these changes

2023-04-04 06:27 UTC, merged